TRI_LAYER_ENABLE   = yes
ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE = yes

RGBLIGHT_ENABLE    = no    # Enable keyboard 'old' RGB lightning
RGB_MATRIX_ENABLE  = no   # Enable keyboard RGB Matrix lightning

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
CIRQUE_PINNACLE_ATTENUATION = CIRQUE_PINNACLE_ATTENUATION = EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X
POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE = yes